--
--
-- LICENSE AND COPYRIGHT INFORMATION:
--
-- The contents of this file are subject to the Mozilla Public
-- License Version 1.1 (the "License"); you may not use this file
-- except in compliance with the License. You may obtain a copy of
-- the License at http://www.mozilla.org/MPL/
-- 
-- Software distributed under the License is distributed on an "AS
-- IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
-- implied. See the License for the specific language governing
-- rights and limitations under the License.
-- 
-- The Original Code is OpenIPMP.
-- 
-- The Initial Developer of the Original Code is Mutable, Inc.
-- Portions created by Mutable, Inc. are
-- Copyright (C) Mutable, Inc. 2002-2006.  All Rights Reserved.
-- 
--

USE OSMS;

SET AUTOCOMMIT=0;

-- *** 
-- *** Load OSMS.ORG_TYPE
-- *** 
INSERT INTO ORG_TYPE ( ORG_TYPE_CODE, ORG_TYPE_NAME, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY) 
VALUES ('DEF', 'Default', 'Default Organization - No Affiliation', 'OSMSLOAD',  'OSMSLOAD'); 
INSERT INTO ORG_TYPE ( ORG_TYPE_CODE, ORG_TYPE_NAME, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY)
VALUES ('ADMIN', 'Administrator', 'Administrator', 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ORG_TYPE ( ORG_TYPE_CODE, ORG_TYPE_NAME, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY)
VALUES ('RET', 'Retailer', 'Retailer or Rights Reseller', 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ORG_TYPE ( ORG_TYPE_CODE, ORG_TYPE_NAME, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY)
VALUES ('SUBSC', 'Subscription Service', 'Subscription Service (or related service)', 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ORG_TYPE ( ORG_TYPE_CODE, ORG_TYPE_NAME, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY)
VALUES ('OWNER', 'Content Owner', 'Content Owner (or acting on behalf of)', 'OSMSLOAD',  'OSMSLOAD'); 

 
-- *** 
-- *** Load OSMS.ORGANIZATION
-- *** 
INSERT INTO ORGANIZATION (
	   ORGANIZATION_ID, ORGANIZATION_NAME, ORG_TYPE_CODE, STATUS_FLAG, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) 
VALUES ( 
	   1, 'DEFAULT', 'DEF', 'A', NULL, 'OSMSLOAD', 'OSMSLOAD');
INSERT INTO ORGANIZATION (
	   ORGANIZATION_ID, ORGANIZATION_NAME, ORG_TYPE_CODE, STATUS_FLAG, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) 
VALUES ( 
	   2, 'Mutable', 'ADMIN', 'A', NULL, 'OSMSLOAD', 'OSMSLOAD'); 

INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
SELECT 'ORGANIZATION', MAX(ORGANIZATION_ID), 'OSMSLOAD', 'OSMSLOAD' FROM ORGANIZATION; 

-- *** 
-- *** Load OSMS.CERTIFICATE_TYPE
-- *** 
INSERT INTO CERTIFICATE_TYPE ( CERTIFICATE_TYPE_CODE, DESCRIPTION, DEFAULT_VALIDITY_DAYS,
MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES ( 
'ID', 'Identity Certificate', 30, NULL, 'OSMSLOAD',  'OSMSLOAD'); 
INSERT INTO CERTIFICATE_TYPE ( CERTIFICATE_TYPE_CODE, DESCRIPTION, DEFAULT_VALIDITY_DAYS,
MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES ( 
'CR', 'Credential Certificate', 36000, NULL, 'OSMSLOAD',  'OSMSLOAD'); 
INSERT INTO CERTIFICATE_TYPE ( CERTIFICATE_TYPE_CODE, DESCRIPTION, DEFAULT_VALIDITY_DAYS,
MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES ( 
'CA', 'Certificate Authority Cert', 730, NULL, 'OSMSLOAD', 'OSMSLOAD'); 


-- *** 
-- *** Load OSMS.ALORITHM
-- *** 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES ( 
1, 'md2WithRSAEncryption', '1.2.840.113549.1.1.2', NULL, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
2, 'sha-1WithRSAEncryption', '1.3.14.3.2.29', NULL, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
3, 'SHA1withRSA', '1.2.840.113549.1.1.5', NULL,  'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
4, 'id-dsa-with-sha1', '1.2.840.10040.2.4.3', NULL,  'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
5, 'pkcs-1 ', '1.2.840.113549.1.1', NULL,  'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
6, 'dhpublicnumber', '1.2.840.10046.2.1', NULL,  'OSMSLOAD', 'OSMSLOAD');
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
7, 'id-dsa ', '1.2.840.10040.2.4.1', NULL,  'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO ALGORITHM (ALGORITHM_ID, NAME, OBJECT_IDENTIFIER, MAINTENANCE_FLAG, LAST_UPDATED_BY, CREATED_BY) VALUES (
8, 'id-keyEncryptionAlgorithm  ', '2.16.840.1.101.2.1.1.22', NULL,  'OSMSLOAD', 'OSMSLOAD'); 

INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
SELECT 'ALGORITHM', MAX(ALGORITHM_ID), 'OSMSLOAD', 'OSMSLOAD' FROM ALGORITHM; 

-- *** 
-- *** Load OSMS.CERTIFICATE
-- *** 
INSERT INTO CERTIFICATE ( CERTIFICATE_ID, CA_CERTIFICATE_ID,
CERTIFICATE_TYPE_CODE, VERSION, NOT_VALID_AFTER_DT, ENCRYPTION_KEY_ID, ALGORITHM_ID,
REVOCATION_ID, ACTION_CODE, STATUS_FLAG, MAINTENANCE_FLAG, LAST_UPDATED_BY, 
SERIAL_NUM, CREATED_BY, NOT_VALID_BEFORE_DT) VALUES ( 
1, 1, 'CA', 3, '01/01/2005', 1, 2, NULL, NULL, NULL, NULL, 
'OSMSLOAD', 'A', 'OSMSLOAD', '01/01/2003'); 

INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
SELECT 'CERTIFICATE', MAX(CERTIFICATE_ID), 'OSMSLOAD', 'OSMSLOAD' FROM CERTIFICATE; 

-- *** 
-- *** Load OSMS.USERS
-- *** 
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, 
ORGANIZATION_ID, CERTIFICATE_ID, SECRET_QUESTION, SECRET_ANSWER, ORG_UNIT_NAME, STATUS_FLAG, MAINTENANCE_FLAG, LAST_UPDATED_BY, 
CREATED_BY) VALUES ( 
1, 'mutableca', 'R4jVULRLzB7PO3xemnZUsQ==', 1, 1, 'Where is MB'
, 'In the cafeteria', 'IT', 'A', NULL, 'OSMSLOAD', 'OSMSLOAD'); 

INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
SELECT 'USERS', MAX(USER_ID), 'OSMSLOAD', 'OSMSLOAD' FROM USERS; 

-- *** 
-- *** Load OSMS.IDENTIFIER_TYPE
-- *** 
INSERT INTO IDENTIFIER_TYPE ( IDENTIFIER_TYPE_CODE, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY ) 
VALUES ('DOI', 'DIGITAL OBJECT IDENTIFIER', 'OSMSLOAD', 'OSMSLOAD' ); 
INSERT INTO IDENTIFIER_TYPE ( IDENTIFIER_TYPE_CODE, DESCRIPTION, LAST_UPDATED_BY, CREATED_BY ) 
VALUES ('GRID', 'GLOBAL RESOURCE IDENTIFIER', 'OSMSLOAD', 'OSMSLOAD' ); 


INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('ALT_IDENTIFIER', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('CERTIFICATE_REVOCATION', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('CIDF', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('CONTENT', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DIGITAL_ITEM', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI_AGENT', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI_ASSERTOR', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI_TITLE', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('EXTENSION', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('GRID', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('GROUPING', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('IPMP_AGREEMENT', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('IPMP_CONSTRAINT', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('IPMP_LICENSE', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('IPMP_PERMISSION', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('LOGIN_HISTORY', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('REVOCATION_LIST', 0, 'OSMSLOAD', 'OSMSLOAD'); 

-- *** 
-- *** Load rows for that control the assignment of doi identifier suffix
-- *** 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI_MASTER_SEQUENCE', 0, 'OSMSLOAD', 'OSMSLOAD'); 
INSERT INTO PK_CONTROL ( TABLE_NAME, CURR_PK_VALUE, LAST_UPDATED_BY, CREATED_BY ) 
VALUES('DOI_INSTANCE_SEQUENCE', 0, 'OSMSLOAD', 'OSMSLOAD'); 

INSERT INTO DOI_PROFILE 
VALUES ('KERN', 'DOI-KERNEL', 'DOI', 'DOI KERNEL METADATA', 'DOI KERNEL METADATA WITHOUT AN APPLICATION PROFILE', 
	    NULL, 'OSMSLOAD', NULL, 'OSMSLOAD', NULL);
		
COMMIT;
