--
--
-- LICENSE AND COPYRIGHT INFORMATION:
--
-- The contents of this file are subject to the Mozilla Public
-- License Version 1.1 (the "License"); you may not use this file
-- except in compliance with the License. You may obtain a copy of
-- the License at http://www.mozilla.org/MPL/
-- 
-- Software distributed under the License is distributed on an "AS
-- IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
-- implied. See the License for the specific language governing
-- rights and limitations under the License.
-- 
-- The Original Code is OpenIPMP.
-- 
-- The Initial Developer of the Original Code is Mutable, Inc.
-- Portions created by Mutable, Inc. are
-- Copyright (C) Mutable, Inc. 2002-2006.  All Rights Reserved.
-- 
--

USE OSMS;

CREATE TABLE GRID (
       GRID_ID              INTEGER NOT NULL,
       GRID                 VARCHAR(18) NOT NULL,
       PRIMARY_ARTIST       VARCHAR(64) NULL,
       PRIMARY_TITLE        VARCHAR(64) NULL,
       ISSUING_COMPANY      VARCHAR(32) NULL,
       XML_STRING           TEXT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (GRID_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1GRID ON GRID
(
       GRID                           ASC
);


CREATE TABLE CERTIFICATE_TYPE (
       CERTIFICATE_TYPE_CODE VARCHAR(2) NOT NULL,
       DESCRIPTION          VARCHAR(32) NULL,
       DEFAULT_VALIDITY_DAYS INTEGER NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (CERTIFICATE_TYPE_CODE)
)TYPE=INNODB;

CREATE TABLE ALGORITHM (
       ALGORITHM_ID         INTEGER NOT NULL,
       NAME                 VARCHAR(32) NULL,
       OBJECT_IDENTIFIER    VARCHAR(64) NULL,
       URL                  VARCHAR(255) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (ALGORITHM_ID)
 )TYPE=INNODB;

CREATE UNIQUE INDEX XAK1ALGORITHM ON ALGORITHM
(
       OBJECT_IDENTIFIER              ASC
);

CREATE TABLE CERTIFICATE (
       CERTIFICATE_ID       INTEGER NOT NULL,
       CERTIFICATE_TYPE_CODE VARCHAR(2) NOT NULL,
       CA_CERTIFICATE_ID    INTEGER NULL,
       VERSION              INTEGER NULL,
       SERIAL_NUM           VARCHAR(32) NOT NULL,
       NOT_VALID_BEFORE_DT  DATETIME NULL,
       NOT_VALID_AFTER_DT   DATETIME NULL,
       CERTIFICATE          BLOB NULL,
       PUBLIC_KEY           BLOB NULL,
       ENCRYPTED_PRIVATE_KEY BLOB NULL,
       ENCRYPTION_KEY_ID    INTEGER NULL,
       ALGORITHM_ID         INTEGER NOT NULL,
       REVOCATION_ID        INTEGER NULL,
       ACTION_CODE          VARCHAR(3) NULL,
       STATUS_FLAG          VARCHAR(1) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (CERTIFICATE_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1CERTIFICATE ON CERTIFICATE
(
       SERIAL_NUM                     ASC
);

CREATE INDEX XIF10CERTIFICATE ON CERTIFICATE
(
       CERTIFICATE_TYPE_CODE          ASC
);

CREATE INDEX XIF7CERTIFICATE ON CERTIFICATE
(
       ALGORITHM_ID                   ASC
);

CREATE INDEX XIF8CERTIFICATE ON CERTIFICATE
(
       CA_CERTIFICATE_ID              ASC
);


CREATE TABLE ORG_TYPE (
       ORG_TYPE_CODE        VARCHAR(5) NOT NULL,
       ORG_TYPE_NAME        VARCHAR(32) NULL,
       DESCRIPTION          VARCHAR(64) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (ORG_TYPE_CODE)
)TYPE=INNODB;

CREATE TABLE ORGANIZATION (
       ORGANIZATION_ID      INTEGER NOT NULL,
       CONTACT_USER         INTEGER NULL,
       ORG_TYPE_CODE        VARCHAR(5) NOT NULL,
       ORGANIZATION_NAME    VARCHAR(128) NOT NULL,
       STATUS_FLAG          VARCHAR(1) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (ORGANIZATION_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1ORGANIZATION ON ORGANIZATION
(
       ORGANIZATION_NAME              ASC
);

CREATE INDEX XIF118ORGANIZATION ON ORGANIZATION
(
       CONTACT_USER                   ASC
);

CREATE INDEX XIF30ORGANIZATION ON ORGANIZATION
(
       ORG_TYPE_CODE                  ASC
);


CREATE TABLE USERS (
       USER_ID              INTEGER NOT NULL,
       USER_NAME            VARCHAR(64) NOT NULL,
       PASSWORD             VARCHAR(32) NULL,
       SECRET_QUESTION      VARCHAR(64) NULL,
       SECRET_ANSWER        VARCHAR(64) NULL,
       SALUTATION           VARCHAR(4) NULL,
       FIRST_NAME           VARCHAR(32) NULL,
       LAST_NAME            VARCHAR(32) NULL,
       SUFFIX               VARCHAR(4) NULL,
       JOB_TITLE            VARCHAR(64) NULL,
       EMAIL_ADDRESS        VARCHAR(128) NULL,
       URL                  VARCHAR(255) NULL,
       ADDRESS_LINE1        VARCHAR(128) NULL,
       ADDRESS_LINE2        VARCHAR(128) NULL,
       ADDRESS_LINE3        VARCHAR(128) NULL,
       CITY                 VARCHAR(128) NULL,
       STATE_CODE           VARCHAR(2) NULL,
       ZIP_CODE             VARCHAR(16) NULL,
       COUNTRY_CODE         VARCHAR(2) NULL,
       ATTENTION_TEXT       VARCHAR(128) NULL,
       MAIN_PHONE_NUMBER    VARCHAR(32) NULL,
       ALT_PHONE_NUMBER     VARCHAR(32) NULL,
       FAX_PHONE_NUMBER     VARCHAR(32) NULL,
       ORG_UNIT_NAME        VARCHAR(32) NULL,
       ORGANIZATION_ID      INTEGER NOT NULL,
       CERTIFICATE_ID       INTEGER NOT NULL,
       STATUS_FLAG          VARCHAR(1) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (USER_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1USERS ON USERS
(
       USER_NAME                      ASC
);

CREATE INDEX XIF24USERS ON USERS
(
       ORGANIZATION_ID                ASC
);

CREATE INDEX XIF79USERS ON USERS
(
       CERTIFICATE_ID                 ASC
);

CREATE TABLE DOI_PROFILE (
       DOI_PROFILE_CODE     VARCHAR(5) NOT NULL,
       PROFILE_NAME         VARCHAR(64) NOT NULL,
       TABLE_NAME           VARCHAR(32) NULL,
       DESC_SHORT           VARCHAR(32) NULL,
       DESC_LONG            VARCHAR(128) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DOI_PROFILE_CODE)
)TYPE=INNODB;


CREATE TABLE DOI (
       DOI_ID               INTEGER NOT NULL,
       DOI_PROFILE_CODE     VARCHAR(5) NOT NULL,
       DOI_IDENTIFIER       VARCHAR(128) NULL,
       STRUCTURAL_TYPE      VARCHAR(32) NULL,
       ISSUED_INTERNALLY    VARCHAR(1) NULL,
       VERSION              VARCHAR(8) NULL,
       XML_STRING           TEXT NULL,
       IS_AUDIO_FLAG        VARCHAR(1) NULL,
       IS_ABSTRACT_FLAG     VARCHAR(1) NULL,
       IS_AUDIOVISUAL_FLAG  VARCHAR(1) NULL,
       IS_VISUAL_FLAG       VARCHAR(1) NULL,
       PRIMARY_TITLE_TEXT   VARCHAR(255) NULL,
       PRIMARY_TITLE_LANGUAGE VARCHAR(16) NULL,
       PRIMARY_AGENT_NAME   VARCHAR(64) NULL,
       PRIMARY_AGENT_TYPE   VARCHAR(16) NULL,
       PRIMARY_AGENT_ROLE   VARCHAR(32) NULL,
       ASSERT_AUTH_TYPE     VARCHAR(16) NULL,
       ASSERT_AUTH_NAME     VARCHAR(64) NULL,
       ASSERT_REG_TYPE      VARCHAR(16) NULL,
       ASSERT_REG_NAME      VARCHAR(64) NULL,
       ASSERT_IDENTIFIER    VARCHAR(128) NULL,
       ASSERT_IDENTIFIER_TYPE VARCHAR(16) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DOI_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1DOI ON DOI
(
       DOI_IDENTIFIER                 ASC
);

CREATE INDEX XIF54DOI ON DOI
(
       DOI_PROFILE_CODE               ASC
);


CREATE TABLE DOI_AGENT (
       DOI_AGENT_ID         INTEGER NOT NULL,
       DOI_ID               INTEGER NULL,
       SEQUENCE             INTEGER NULL,
       AGENT_TYPE           VARCHAR(16) NULL,
       AGENT_NAME           VARCHAR(64) NULL,
       ROLE1                VARCHAR(32) NULL,
       ROLE2                VARCHAR(32) NULL,
       ROLE3                VARCHAR(32) NULL,
       ROLE4                VARCHAR(32) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DOI_AGENT_ID)
)TYPE=INNODB;

CREATE INDEX XIF73DOI_AGENT ON DOI_AGENT
(
       DOI_ID                         ASC
);


CREATE TABLE DOI_TITLE (
       TITLE_ID             INTEGER NOT NULL,
       SEQUENCE             INTEGER NULL,
       TITLE_TEXT           VARCHAR(255) NULL,
       LANGUAGE             VARCHAR(16) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (TITLE_ID)
)TYPE=INNODB;


CREATE TABLE DOI_TITLE_REL (
       DOI_ID               INTEGER NOT NULL,
       TITLE_ID             INTEGER NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DOI_ID, TITLE_ID)
)TYPE=INNODB;

CREATE INDEX XIF67DOI_TITLE_REL ON DOI_TITLE_REL
(
       DOI_ID                         ASC
);

CREATE INDEX XIF68DOI_TITLE_REL ON DOI_TITLE_REL
(
       TITLE_ID                       ASC
);

CREATE TABLE LOGIN_HISTORY (
       LOGIN_ID             INTEGER NOT NULL,
       USER_ID              INTEGER NOT NULL,
       IP_ADDRESS           VARCHAR(32) NULL,
       LOGIN_TIME           DATETIME NULL,
       LOGOFF_TIME          DATETIME NULL,
       CLIENT_LOGIN_TIME    DATETIME NULL,
       CLIENT_LOGOFF_TIME   DATETIME NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (LOGIN_ID)
)TYPE=INNODB;

CREATE INDEX XIF66LOGIN_HISTORY ON LOGIN_HISTORY
(
       USER_ID                        ASC
);


CREATE TABLE IDENTIFIER_TYPE (
       IDENTIFIER_TYPE_CODE VARCHAR(5) NOT NULL,
       DESCRIPTION          VARCHAR(64) NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (IDENTIFIER_TYPE_CODE)
)TYPE=INNODB;


CREATE TABLE ALT_IDENTIFIER (
       ALT_IDENTIFIER_ID    INTEGER NOT NULL,
       IDENTIFIER_TYPE_CODE VARCHAR(5) NOT NULL,
       IDENTIFIER           VARCHAR(128) NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (ALT_IDENTIFIER_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1ALT_IDENTIFIER ON ALT_IDENTIFIER
(
       IDENTIFIER                     ASC,
       IDENTIFIER_TYPE_CODE           ASC
);

CREATE INDEX XIF57ALT_IDENTIFIER ON ALT_IDENTIFIER
(
       IDENTIFIER_TYPE_CODE           ASC
);


CREATE TABLE DOI_ALT_IDENTIFIER (
       DOI_ID               INTEGER NOT NULL,
       ALT_IDENTIFIER_ID    INTEGER NOT NULL,
       SEQUENCE             INTEGER NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DOI_ID, ALT_IDENTIFIER_ID)
)TYPE=INNODB;

CREATE INDEX XIF55DOI_ALT_IDENTIFIER ON DOI_ALT_IDENTIFIER
(
       DOI_ID                         ASC
);

CREATE INDEX XIF56DOI_ALT_IDENTIFIER ON DOI_ALT_IDENTIFIER
(
       ALT_IDENTIFIER_ID              ASC
);


CREATE TABLE PK_CONTROL (
       TABLE_NAME           VARCHAR(64) NOT NULL,
       CURR_PK_VALUE        INTEGER NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (TABLE_NAME)
)TYPE=INNODB;

CREATE TABLE CONTENT (
       CONTENT_ID           INTEGER NOT NULL,
       IDENTIFIER_TYPE_CODE VARCHAR(5) NULL,
       PRIMARY_IDENTIFIER   VARCHAR(128) NULL,
       PRIMARY_ARTIST       VARCHAR(64) NULL,
       PRIMARY_TITLE        VARCHAR(64) NULL,
       RELEASE_DATE         DATETIME NULL,
       LICENSE_BEGIN_DATE   DATETIME NULL,
       LICENSE_TYPE         VARCHAR(8) NULL,
       REGISTERED_BY        INTEGER NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (CONTENT_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1CONTENT ON CONTENT
(
       PRIMARY_IDENTIFIER             ASC,
       IDENTIFIER_TYPE_CODE           ASC
);

CREATE INDEX XIF100CONTENT ON CONTENT
(
       REGISTERED_BY                  ASC
);

CREATE INDEX XIF105CONTENT ON CONTENT
(
       IDENTIFIER_TYPE_CODE           ASC
);

CREATE TABLE CONTENT_GRID (
       CONTENT_ID           INTEGER NOT NULL,
       GRID_ID              INTEGER NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (CONTENT_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1CONTENT_GRID ON CONTENT_GRID
(
       GRID_ID                        ASC
);

CREATE TABLE CONTENT_DOI (
       CONTENT_ID           INTEGER NOT NULL,
       DOI_ID               INTEGER NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (CONTENT_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1CONTENT_DOI ON CONTENT_DOI
(
       DOI_ID                         ASC
);

CREATE TABLE DIGITAL_ITEM (
       DIGITAL_ITEM_ID      INTEGER NOT NULL,
       CA_CERTIFICATE_ID    INTEGER NULL,
       CONTENT_ID           INTEGER NOT NULL,
       DOI_ID               INTEGER NOT NULL,
       MIME_TYPE            VARCHAR(128) NULL,
       ENCRYPTED_KEY        BLOB NULL,
       KEY_LENGTH           INTEGER NULL,
       KEY_ALGORITHM_ID     INTEGER NULL,
       ENCRYPTION_KEY_ID    INTEGER NULL,
       CONTENT_DIGEST       VARCHAR(32) NULL,
       DIGEST_ALGORITHM_ID  INTEGER NULL,
       CONTENT_SIGNATURE    BLOB NULL,
       SIG_ALGORITHM_ID     INTEGER NULL,
       WATERMARK_DATA       VARCHAR(255) NULL,
       TOOL_IDENTIFIER      INTEGER NULL,
       RIGHTS_HOST_URL      VARCHAR(255) NULL,
       RIGHTS_HOST_PORT     VARCHAR(8) NULL,
       LICENSE_TYPE         VARCHAR(8) NULL,
       IS_REVOKED_FLAG      VARCHAR(1) NULL,
       IS_PROTECTED_FLAG    VARCHAR(1) NULL,
       REGISTERED_BY        INTEGER NOT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (DIGITAL_ITEM_ID)
)TYPE=INNODB;

CREATE INDEX XIF119DIGITAL_ITEM ON DIGITAL_ITEM
(
       CA_CERTIFICATE_ID              ASC
);

CREATE INDEX XIF50DIGITAL_ITEM ON DIGITAL_ITEM
(
       DOI_ID                         ASC
);

CREATE INDEX XIF78DIGITAL_ITEM ON DIGITAL_ITEM
(
       CONTENT_ID                     ASC
);

CREATE INDEX XIF80DIGITAL_ITEM ON DIGITAL_ITEM
(
       KEY_ALGORITHM_ID               ASC
);

CREATE INDEX XIF81DIGITAL_ITEM ON DIGITAL_ITEM
(
       DIGEST_ALGORITHM_ID            ASC
);

CREATE INDEX XIF82DIGITAL_ITEM ON DIGITAL_ITEM
(
       SIG_ALGORITHM_ID               ASC
);

CREATE INDEX XIF86DIGITAL_ITEM ON DIGITAL_ITEM
(
       REGISTERED_BY                  ASC
);


CREATE TABLE IPMP_AGREEMENT (
       AGREEMENT_ID         INTEGER NOT NULL,
       CONTENT_ID           INTEGER NULL,
       START_DATE           DATETIME NULL,
       END_DATE             DATETIME NULL,
       USER_LICENSE_LIMIT   INTEGER NULL,
       GLOBAL_LICENSE_LIMIT INTEGER NULL,
       LICENSE_TYPE         VARCHAR(8) NULL,
       ASSIGNED_TO_USER     INTEGER NOT NULL,
       ASSIGNED_TO_GROUP    INTEGER NULL,
       REGISTERED_BY        INTEGER NOT NULL,
       XML_STRING           TEXT NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (AGREEMENT_ID)
)TYPE=INNODB;

CREATE INDEX XIF87IPMP_AGREEMENT ON IPMP_AGREEMENT
(
       REGISTERED_BY                  ASC
);

CREATE INDEX XIF88IPMP_AGREEMENT ON IPMP_AGREEMENT
(
       ASSIGNED_TO_USER               ASC
);

CREATE INDEX XIF89IPMP_AGREEMENT ON IPMP_AGREEMENT
(
       ASSIGNED_TO_GROUP              ASC
);

CREATE INDEX XIF90IPMP_AGREEMENT ON IPMP_AGREEMENT
(
       CONTENT_ID                     ASC
);


CREATE TABLE IPMP_LICENSE (
       LICENSE_ID           INTEGER NOT NULL,
       CA_CERTIFICATE_ID    INTEGER NULL,
       LICENSE_IDENTIFIER   VARCHAR(128) NULL,
       DIGITAL_ITEM_ID      INTEGER NOT NULL,
       ISSUED_TO_USER       INTEGER NOT NULL,
       AGREEMENT_ID         INTEGER NOT NULL,
       LICENSE_TYPE         VARCHAR(8) NULL,
       XML_STRING           TEXT NULL,
       LICENSE_DIGEST       VARCHAR(32) NULL,
       DIGEST_ALGORITHM_ID  INTEGER NULL,
       LICENSE_SIGNATURE    BLOB NULL,
       SIG_ALGORITHM_ID     INTEGER NULL,
       MAINTENANCE_FLAG     VARCHAR(1) NULL,
       LAST_UPDATED_BY      VARCHAR(16) NULL,
       LAST_UPDATED_ON      DATETIME NULL,
       CREATED_BY           VARCHAR(16) NULL,
       CREATED_ON           DATETIME NULL,
       PRIMARY KEY (LICENSE_ID)
)TYPE=INNODB;

CREATE UNIQUE INDEX XAK1IPMP_LICENSE ON IPMP_LICENSE
(
       LICENSE_IDENTIFIER             ASC
);

CREATE INDEX XIF101IPMP_LICENSE ON IPMP_LICENSE
(
       AGREEMENT_ID                   ASC
);

CREATE INDEX XIF102IPMP_LICENSE ON IPMP_LICENSE
(
       ISSUED_TO_USER                 ASC
);

CREATE INDEX XIF103IPMP_LICENSE ON IPMP_LICENSE
(
       SIG_ALGORITHM_ID               ASC
);

CREATE INDEX XIF104IPMP_LICENSE ON IPMP_LICENSE
(
       DIGEST_ALGORITHM_ID            ASC
);

CREATE INDEX XIF111IPMP_LICENSE ON IPMP_LICENSE
(
       DIGITAL_ITEM_ID                ASC
);

CREATE INDEX XIF120IPMP_LICENSE ON IPMP_LICENSE
(
       CA_CERTIFICATE_ID              ASC
);


ALTER TABLE CERTIFICATE
       ADD  ( FOREIGN KEY (CERTIFICATE_TYPE_CODE)
                             REFERENCES CERTIFICATE_TYPE(CERTIFICATE_TYPE_CODE)) ;

ALTER TABLE CERTIFICATE
       ADD  ( FOREIGN KEY (CA_CERTIFICATE_ID)
                             REFERENCES CERTIFICATE(CERTIFICATE_ID)) ;


ALTER TABLE CERTIFICATE
       ADD  ( FOREIGN KEY (ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE ORGANIZATION
       ADD  ( FOREIGN KEY (CONTACT_USER)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE ORGANIZATION
       ADD  ( FOREIGN KEY (ORG_TYPE_CODE)
                             REFERENCES ORG_TYPE(ORG_TYPE_CODE)) ;


ALTER TABLE USERS
       ADD  ( FOREIGN KEY (CERTIFICATE_ID)
                             REFERENCES CERTIFICATE(CERTIFICATE_ID)) ;


ALTER TABLE USERS
       ADD  ( FOREIGN KEY (ORGANIZATION_ID)
                             REFERENCES ORGANIZATION(ORGANIZATION_ID)) ;


ALTER TABLE DOI
       ADD  ( FOREIGN KEY (DOI_PROFILE_CODE)
                             REFERENCES DOI_PROFILE(DOI_PROFILE_CODE)) ;


ALTER TABLE DOI_AGENT
       ADD  ( FOREIGN KEY (DOI_ID)
                             REFERENCES DOI(DOI_ID)) ;


ALTER TABLE DOI_TITLE_REL
       ADD  ( FOREIGN KEY (TITLE_ID)
                             REFERENCES DOI_TITLE(TITLE_ID)) ;


ALTER TABLE DOI_TITLE_REL
       ADD  ( FOREIGN KEY (DOI_ID)
                             REFERENCES DOI(DOI_ID)) ;


ALTER TABLE LOGIN_HISTORY
       ADD  ( FOREIGN KEY (USER_ID)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE ALT_IDENTIFIER
       ADD  ( FOREIGN KEY (IDENTIFIER_TYPE_CODE)
                             REFERENCES IDENTIFIER_TYPE(IDENTIFIER_TYPE_CODE)) ;


ALTER TABLE DOI_ALT_IDENTIFIER
       ADD  ( FOREIGN KEY (ALT_IDENTIFIER_ID)
                             REFERENCES ALT_IDENTIFIER(ALT_IDENTIFIER_ID)) ;


ALTER TABLE DOI_ALT_IDENTIFIER
       ADD  ( FOREIGN KEY (DOI_ID)
                             REFERENCES DOI(DOI_ID)) ;


ALTER TABLE CONTENT
       ADD  ( FOREIGN KEY (IDENTIFIER_TYPE_CODE)
                             REFERENCES IDENTIFIER_TYPE(IDENTIFIER_TYPE_CODE)) ;


ALTER TABLE CONTENT
       ADD  ( FOREIGN KEY (REGISTERED_BY)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE CONTENT_GRID
       ADD  ( FOREIGN KEY (GRID_ID)
                             REFERENCES GRID(GRID_ID)) ;

ALTER TABLE CONTENT_GRID
       ADD  ( FOREIGN KEY (CONTENT_ID)
                             REFERENCES CONTENT(CONTENT_ID) ) ;


ALTER TABLE CONTENT_DOI
       ADD  ( FOREIGN KEY (DOI_ID)
                             REFERENCES DOI(DOI_ID)) ;

ALTER TABLE CONTENT_DOI
       ADD  ( FOREIGN KEY (CONTENT_ID)
                             REFERENCES CONTENT(CONTENT_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (CA_CERTIFICATE_ID)
                             REFERENCES CERTIFICATE(CERTIFICATE_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (REGISTERED_BY)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (SIG_ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (DIGEST_ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (KEY_ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (CONTENT_ID)
                             REFERENCES CONTENT(CONTENT_ID)) ;


ALTER TABLE DIGITAL_ITEM
       ADD  ( FOREIGN KEY (DOI_ID)
                             REFERENCES DOI(DOI_ID)) ;


ALTER TABLE IPMP_AGREEMENT
       ADD  ( FOREIGN KEY (CONTENT_ID)
                             REFERENCES CONTENT(CONTENT_ID)) ;


ALTER TABLE IPMP_AGREEMENT
       ADD  ( FOREIGN KEY (ASSIGNED_TO_USER)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE IPMP_AGREEMENT
       ADD  ( FOREIGN KEY (REGISTERED_BY)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (CA_CERTIFICATE_ID)
                             REFERENCES CERTIFICATE(CERTIFICATE_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (DIGITAL_ITEM_ID)
                             REFERENCES DIGITAL_ITEM(DIGITAL_ITEM_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (DIGEST_ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (SIG_ALGORITHM_ID)
                             REFERENCES ALGORITHM(ALGORITHM_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (ISSUED_TO_USER)
                             REFERENCES USERS(USER_ID)) ;


ALTER TABLE IPMP_LICENSE
       ADD  ( FOREIGN KEY (AGREEMENT_ID)
                             REFERENCES IPMP_AGREEMENT(AGREEMENT_ID)) ;




