/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsLicenseResponse
 */

#include "OsmsLicenseResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsLicenseResponse type of object
 */
int Axis_Serialize_OsmsLicenseResponse(OsmsLicenseResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsLicenseResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsLicenseResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsLicenseResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsLicenseResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsLicenseResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsLicenseResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsLicenseResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("license", (void*)(param->license), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsLicenseResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsLicenseResponse type of object
 */
int Axis_DeSerialize_OsmsLicenseResponse(OsmsLicenseResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->license = pIWSDZ->getElementAsString("license",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsLicenseResponse(OsmsLicenseResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsLicenseResponse* pNew = new OsmsLicenseResponse[nSize];
			memcpy(pNew, pObj, sizeof(OsmsLicenseResponse)*nSize/2);
			memset(pObj, 0, sizeof(OsmsLicenseResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsLicenseResponse[nSize];
		}
	}
	else
		return new OsmsLicenseResponse;
}

/*
 * This static method delete a OsmsLicenseResponse type of object
 */
void Axis_Delete_OsmsLicenseResponse(OsmsLicenseResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsLicenseResponse type of object
 */
int Axis_GetSize_OsmsLicenseResponse()
{
	return sizeof(OsmsLicenseResponse);
}

OsmsLicenseResponse::OsmsLicenseResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &license, 0, sizeof( xsd__string));
}

OsmsLicenseResponse::~OsmsLicenseResponse()
{
	/*delete any pointer and array members here*/
}
