/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsRegisterUserRequest
 */

#include "OsmsRegisterUserRequest.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsRegisterUserRequest type of object
 */
int Axis_Serialize_OsmsRegisterUserRequest(OsmsRegisterUserRequest* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserRequest, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsRegisterUserRequest, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterUserRequest, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterUserRequest, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsRegisterUserRequest, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("emailAddress", (void*)(param->emailAddress), XSD_STRING);
	pSZ->serializeAsElement("password", (void*)(param->password), XSD_STRING);
	pSZ->serializeAsElement("passwordConfirm", (void*)(param->passwordConfirm), XSD_STRING);
	pSZ->serializeAsElement("userName", (void*)(param->userName), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsRegisterUserRequest, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsRegisterUserRequest type of object
 */
int Axis_DeSerialize_OsmsRegisterUserRequest(OsmsRegisterUserRequest* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->emailAddress = pIWSDZ->getElementAsString("emailAddress",0);
	param->password = pIWSDZ->getElementAsString("password",0);
	param->passwordConfirm = pIWSDZ->getElementAsString("passwordConfirm",0);
	param->userName = pIWSDZ->getElementAsString("userName",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsRegisterUserRequest(OsmsRegisterUserRequest* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsRegisterUserRequest* pNew = new OsmsRegisterUserRequest[nSize];
			memcpy(pNew, pObj, sizeof(OsmsRegisterUserRequest)*nSize/2);
			memset(pObj, 0, sizeof(OsmsRegisterUserRequest)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsRegisterUserRequest[nSize];
		}
	}
	else
		return new OsmsRegisterUserRequest;
}

/*
 * This static method delete a OsmsRegisterUserRequest type of object
 */
void Axis_Delete_OsmsRegisterUserRequest(OsmsRegisterUserRequest* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsRegisterUserRequest type of object
 */
int Axis_GetSize_OsmsRegisterUserRequest()
{
	return sizeof(OsmsRegisterUserRequest);
}

OsmsRegisterUserRequest::OsmsRegisterUserRequest()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &emailAddress, 0, sizeof( xsd__string));
	memset( &password, 0, sizeof( xsd__string));
	memset( &passwordConfirm, 0, sizeof( xsd__string));
	memset( &userName, 0, sizeof( xsd__string));
}

OsmsRegisterUserRequest::~OsmsRegisterUserRequest()
{
	/*delete any pointer and array members here*/
}
