/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsRegisterUserResponse
 */

#include "OsmsRegisterUserResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsRegisterUserResponse type of object
 */
int Axis_Serialize_OsmsRegisterUserResponse(OsmsRegisterUserResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsRegisterUserResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterUserResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterUserResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterUserResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsRegisterUserResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("userName", (void*)(param->userName), XSD_STRING);
	pSZ->serializeAsElement("userSecurityStore", (void*)&(param->userSecurityStore), XSD_BASE64BINARY);

	pSZ->serialize("</", Axis_TypeName_OsmsRegisterUserResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsRegisterUserResponse type of object
 */
int Axis_DeSerialize_OsmsRegisterUserResponse(OsmsRegisterUserResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->userName = pIWSDZ->getElementAsString("userName",0);
	xsd__base64Binary* p_userSecurityStore = (pIWSDZ->getElementAsBase64Binary("userSecurityStore",0));
	param->userSecurityStore = *p_userSecurityStore;
	delete p_userSecurityStore;
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsRegisterUserResponse(OsmsRegisterUserResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsRegisterUserResponse* pNew = new OsmsRegisterUserResponse[nSize];
			memcpy(pNew, pObj, sizeof(OsmsRegisterUserResponse)*nSize/2);
			memset(pObj, 0, sizeof(OsmsRegisterUserResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsRegisterUserResponse[nSize];
		}
	}
	else
		return new OsmsRegisterUserResponse;
}

/*
 * This static method delete a OsmsRegisterUserResponse type of object
 */
void Axis_Delete_OsmsRegisterUserResponse(OsmsRegisterUserResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsRegisterUserResponse type of object
 */
int Axis_GetSize_OsmsRegisterUserResponse()
{
	return sizeof(OsmsRegisterUserResponse);
}

OsmsRegisterUserResponse::OsmsRegisterUserResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &userName, 0, sizeof( xsd__string));
	memset( &userSecurityStore, 0, sizeof( xsd__base64Binary));
}

OsmsRegisterUserResponse::~OsmsRegisterUserResponse()
{
	/*delete any pointer and array members here*/
}
