/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsCreateUserRequest
 */

#if !defined(__OSMSCREATEUSERREQUEST_PARAM_H__INCLUDED_)
#define __OSMSCREATEUSERREQUEST_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_OsmsCreateUserRequest = "http://message.ws.server.osms.mutable.com";
static const char* Axis_TypeName_OsmsCreateUserRequest = "OsmsCreateUserRequest";

class OsmsCreateUserRequest
{
public:
	xsd__string addressLine1;
	xsd__string addressLine2;
	xsd__string addressLine3;
	xsd__string altPhoneNumber;
	xsd__string city;
	xsd__string country;
	xsd__string emailAddress;
	xsd__string faxPhoneNumber;
	xsd__string firstName;
	xsd__string lastName;
	xsd__string mainPhoneNumber;
	xsd__string organizationName;
	xsd__string organizationUnit;
	xsd__string password;
	xsd__string salutation;
	xsd__string secretAnswer;
	xsd__string secretQuestion;
	xsd__string state;
	xsd__string suffix;
	xsd__string userName;
	xsd__string zipCode;
	OsmsCreateUserRequest();
	virtual ~OsmsCreateUserRequest();
};

#endif /* !defined(__OSMSCREATEUSERREQUEST_PARAM_H__INCLUDED_)*/
