/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsRegisterDigitalItemInstanceResponse
 */

#include "OsmsRegisterDigitalItemInstanceResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsRegisterDigitalItemInstanceResponse type of object
 */
int Axis_Serialize_OsmsRegisterDigitalItemInstanceResponse(OsmsRegisterDigitalItemInstanceResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsRegisterDigitalItemInstanceResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsRegisterDigitalItemInstanceResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("auxDataXml", (void*)(param->auxDataXml), XSD_STRING);
	pSZ->serializeAsElement("metadataType", (void*)(param->metadataType), XSD_STRING);
	pSZ->serializeAsElement("metadataXml", (void*)(param->metadataXml), XSD_STRING);
	pSZ->serializeAsElement("signatureXml", (void*)(param->signatureXml), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsRegisterDigitalItemInstanceResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsRegisterDigitalItemInstanceResponse type of object
 */
int Axis_DeSerialize_OsmsRegisterDigitalItemInstanceResponse(OsmsRegisterDigitalItemInstanceResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->auxDataXml = pIWSDZ->getElementAsString("auxDataXml",0);
	param->metadataType = pIWSDZ->getElementAsString("metadataType",0);
	param->metadataXml = pIWSDZ->getElementAsString("metadataXml",0);
	param->signatureXml = pIWSDZ->getElementAsString("signatureXml",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsRegisterDigitalItemInstanceResponse(OsmsRegisterDigitalItemInstanceResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsRegisterDigitalItemInstanceResponse* pNew = new OsmsRegisterDigitalItemInstanceResponse[nSize];
			memcpy(pNew, pObj, sizeof(OsmsRegisterDigitalItemInstanceResponse)*nSize/2);
			memset(pObj, 0, sizeof(OsmsRegisterDigitalItemInstanceResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsRegisterDigitalItemInstanceResponse[nSize];
		}
	}
	else
		return new OsmsRegisterDigitalItemInstanceResponse;
}

/*
 * This static method delete a OsmsRegisterDigitalItemInstanceResponse type of object
 */
void Axis_Delete_OsmsRegisterDigitalItemInstanceResponse(OsmsRegisterDigitalItemInstanceResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsRegisterDigitalItemInstanceResponse type of object
 */
int Axis_GetSize_OsmsRegisterDigitalItemInstanceResponse()
{
	return sizeof(OsmsRegisterDigitalItemInstanceResponse);
}

OsmsRegisterDigitalItemInstanceResponse::OsmsRegisterDigitalItemInstanceResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &auxDataXml, 0, sizeof( xsd__string));
	memset( &metadataType, 0, sizeof( xsd__string));
	memset( &metadataXml, 0, sizeof( xsd__string));
	memset( &signatureXml, 0, sizeof( xsd__string));
}

OsmsRegisterDigitalItemInstanceResponse::~OsmsRegisterDigitalItemInstanceResponse()
{
	/*delete any pointer and array members here*/
}
