/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsUserLoginRequest
 */

#include "OsmsUserLoginRequest.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsUserLoginRequest type of object
 */
int Axis_Serialize_OsmsUserLoginRequest(OsmsUserLoginRequest* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsUserLoginRequest, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsUserLoginRequest, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsUserLoginRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsUserLoginRequest, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsUserLoginRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsUserLoginRequest, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsUserLoginRequest, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("password", (void*)(param->password), XSD_STRING);
	pSZ->serializeAsElement("userName", (void*)(param->userName), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsUserLoginRequest, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsUserLoginRequest type of object
 */
int Axis_DeSerialize_OsmsUserLoginRequest(OsmsUserLoginRequest* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->password = pIWSDZ->getElementAsString("password",0);
	param->userName = pIWSDZ->getElementAsString("userName",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsUserLoginRequest(OsmsUserLoginRequest* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsUserLoginRequest* pNew = new OsmsUserLoginRequest[nSize];
			memcpy(pNew, pObj, sizeof(OsmsUserLoginRequest)*nSize/2);
			memset(pObj, 0, sizeof(OsmsUserLoginRequest)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsUserLoginRequest[nSize];
		}
	}
	else
		return new OsmsUserLoginRequest;
}

/*
 * This static method delete a OsmsUserLoginRequest type of object
 */
void Axis_Delete_OsmsUserLoginRequest(OsmsUserLoginRequest* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsUserLoginRequest type of object
 */
int Axis_GetSize_OsmsUserLoginRequest()
{
	return sizeof(OsmsUserLoginRequest);
}

OsmsUserLoginRequest::OsmsUserLoginRequest()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &password, 0, sizeof( xsd__string));
	memset( &userName, 0, sizeof( xsd__string));
}

OsmsUserLoginRequest::~OsmsUserLoginRequest()
{
	/*delete any pointer and array members here*/
}
