/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsRightsAuthorizationResponse
 */

#include "OsmsRightsAuthorizationResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsRightsAuthorizationResponse type of object
 */
int Axis_Serialize_OsmsRightsAuthorizationResponse(OsmsRightsAuthorizationResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsRightsAuthorizationResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsRightsAuthorizationResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRightsAuthorizationResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRightsAuthorizationResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRightsAuthorizationResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRightsAuthorizationResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsRightsAuthorizationResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("transactionId", (void*)(param->transactionId), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsRightsAuthorizationResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsRightsAuthorizationResponse type of object
 */
int Axis_DeSerialize_OsmsRightsAuthorizationResponse(OsmsRightsAuthorizationResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->transactionId = pIWSDZ->getElementAsString("transactionId",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsRightsAuthorizationResponse(OsmsRightsAuthorizationResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsRightsAuthorizationResponse* pNew = new OsmsRightsAuthorizationResponse[nSize];
			memcpy(pNew, pObj, sizeof(OsmsRightsAuthorizationResponse)*nSize/2);
			memset(pObj, 0, sizeof(OsmsRightsAuthorizationResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsRightsAuthorizationResponse[nSize];
		}
	}
	else
		return new OsmsRightsAuthorizationResponse;
}

/*
 * This static method delete a OsmsRightsAuthorizationResponse type of object
 */
void Axis_Delete_OsmsRightsAuthorizationResponse(OsmsRightsAuthorizationResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsRightsAuthorizationResponse type of object
 */
int Axis_GetSize_OsmsRightsAuthorizationResponse()
{
	return sizeof(OsmsRightsAuthorizationResponse);
}

OsmsRightsAuthorizationResponse::OsmsRightsAuthorizationResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &transactionId, 0, sizeof( xsd__string));
}

OsmsRightsAuthorizationResponse::~OsmsRightsAuthorizationResponse()
{
	/*delete any pointer and array members here*/
}
