/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsQueryRequest
 */

#include "OsmsQueryRequest.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsQueryRequest type of object
 */
int Axis_Serialize_OsmsQueryRequest(OsmsQueryRequest* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsQueryRequest, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsQueryRequest, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsQueryRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsQueryRequest, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsQueryRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsQueryRequest, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsQueryRequest, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("type", (void*)(param->type), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsQueryRequest, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsQueryRequest type of object
 */
int Axis_DeSerialize_OsmsQueryRequest(OsmsQueryRequest* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->type = pIWSDZ->getElementAsString("type",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsQueryRequest(OsmsQueryRequest* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsQueryRequest* pNew = new OsmsQueryRequest[nSize];
			memcpy(pNew, pObj, sizeof(OsmsQueryRequest)*nSize/2);
			memset(pObj, 0, sizeof(OsmsQueryRequest)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsQueryRequest[nSize];
		}
	}
	else
		return new OsmsQueryRequest;
}

/*
 * This static method delete a OsmsQueryRequest type of object
 */
void Axis_Delete_OsmsQueryRequest(OsmsQueryRequest* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsQueryRequest type of object
 */
int Axis_GetSize_OsmsQueryRequest()
{
	return sizeof(OsmsQueryRequest);
}

OsmsQueryRequest::OsmsQueryRequest()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &type, 0, sizeof( xsd__string));
}

OsmsQueryRequest::~OsmsQueryRequest()
{
	/*delete any pointer and array members here*/
}
