/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsRegisterContentAssignIdentifierRequest
 */

#include "OsmsRegisterContentAssignIdentifierRequest.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsRegisterContentAssignIdentifierRequest type of object
 */
int Axis_Serialize_OsmsRegisterContentAssignIdentifierRequest(OsmsRegisterContentAssignIdentifierRequest* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsRegisterContentAssignIdentifierRequest, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsRegisterContentAssignIdentifierRequest, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("metadataType", (void*)(param->metadataType), XSD_STRING);
	pSZ->serializeAsElement("metadataXml", (void*)(param->metadataXml), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsRegisterContentAssignIdentifierRequest, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsRegisterContentAssignIdentifierRequest type of object
 */
int Axis_DeSerialize_OsmsRegisterContentAssignIdentifierRequest(OsmsRegisterContentAssignIdentifierRequest* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->metadataType = pIWSDZ->getElementAsString("metadataType",0);
	param->metadataXml = pIWSDZ->getElementAsString("metadataXml",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsRegisterContentAssignIdentifierRequest(OsmsRegisterContentAssignIdentifierRequest* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsRegisterContentAssignIdentifierRequest* pNew = new OsmsRegisterContentAssignIdentifierRequest[nSize];
			memcpy(pNew, pObj, sizeof(OsmsRegisterContentAssignIdentifierRequest)*nSize/2);
			memset(pObj, 0, sizeof(OsmsRegisterContentAssignIdentifierRequest)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsRegisterContentAssignIdentifierRequest[nSize];
		}
	}
	else
		return new OsmsRegisterContentAssignIdentifierRequest;
}

/*
 * This static method delete a OsmsRegisterContentAssignIdentifierRequest type of object
 */
void Axis_Delete_OsmsRegisterContentAssignIdentifierRequest(OsmsRegisterContentAssignIdentifierRequest* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsRegisterContentAssignIdentifierRequest type of object
 */
int Axis_GetSize_OsmsRegisterContentAssignIdentifierRequest()
{
	return sizeof(OsmsRegisterContentAssignIdentifierRequest);
}

OsmsRegisterContentAssignIdentifierRequest::OsmsRegisterContentAssignIdentifierRequest()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &metadataType, 0, sizeof( xsd__string));
	memset( &metadataXml, 0, sizeof( xsd__string));
}

OsmsRegisterContentAssignIdentifierRequest::~OsmsRegisterContentAssignIdentifierRequest()
{
	/*delete any pointer and array members here*/
}
