/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsQueryResponse
 */

#include "OsmsQueryResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsQueryResponse type of object
 */
int Axis_Serialize_OsmsQueryResponse(OsmsQueryResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_OsmsQueryResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_OsmsQueryResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_OsmsQueryResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsQueryResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_OsmsQueryResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_OsmsQueryResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_OsmsQueryResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("heading", (void*)(param->heading), XSD_STRING);
	pSZ->serializeAsElement("length", (void*)&(param->length), XSD_INT);
	pSZ->serializeAsElement("results", (void*)(param->results), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_OsmsQueryResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a OsmsQueryResponse type of object
 */
int Axis_DeSerialize_OsmsQueryResponse(OsmsQueryResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->heading = pIWSDZ->getElementAsString("heading",0);
	xsd__int* p_length = (pIWSDZ->getElementAsInt("length",0));
	param->length = *p_length;
	delete p_length;
	param->results = pIWSDZ->getElementAsString("results",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_OsmsQueryResponse(OsmsQueryResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsQueryResponse* pNew = new OsmsQueryResponse[nSize];
			memcpy(pNew, pObj, sizeof(OsmsQueryResponse)*nSize/2);
			memset(pObj, 0, sizeof(OsmsQueryResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsQueryResponse[nSize];
		}
	}
	else
		return new OsmsQueryResponse;
}

/*
 * This static method delete a OsmsQueryResponse type of object
 */
void Axis_Delete_OsmsQueryResponse(OsmsQueryResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsQueryResponse type of object
 */
int Axis_GetSize_OsmsQueryResponse()
{
	return sizeof(OsmsQueryResponse);
}

OsmsQueryResponse::OsmsQueryResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &heading, 0, sizeof( xsd__string));
	memset( &length, 0, sizeof( xsd__int));
	memset( &results, 0, sizeof( xsd__string));
}

OsmsQueryResponse::~OsmsQueryResponse()
{
	/*delete any pointer and array members here*/
}
