/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsUserLoginRequest
 */

#if !defined(__OSMSUSERLOGINREQUEST_PARAM_H__INCLUDED_)
#define __OSMSUSERLOGINREQUEST_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_OsmsUserLoginRequest = "http://message.ws.server.osms.mutable.com";
static const char* Axis_TypeName_OsmsUserLoginRequest = "OsmsUserLoginRequest";

class OsmsUserLoginRequest
{
public:
	xsd__string password;
	xsd__string userName;
	OsmsUserLoginRequest();
	virtual ~OsmsUserLoginRequest();
};

#endif /* !defined(__OSMSUSERLOGINREQUEST_PARAM_H__INCLUDED_)*/
