/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type OsmsUserLogoutRequest
 */

#include "OsmsUserLogoutRequest.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a OsmsUserLogoutRequest type of object
 */
int Axis_Serialize_OsmsUserLogoutRequest(OsmsUserLogoutRequest* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
return 0;	}

/*
 * This static method deserialize a OsmsUserLogoutRequest type of object
 */
int Axis_DeSerialize_OsmsUserLogoutRequest(OsmsUserLogoutRequest* param, IWrapperSoapDeSerializer* pIWSDZ)
{
return 0;	}

void* Axis_Create_OsmsUserLogoutRequest(OsmsUserLogoutRequest* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			OsmsUserLogoutRequest* pNew = new OsmsUserLogoutRequest[nSize];
			memcpy(pNew, pObj, sizeof(OsmsUserLogoutRequest)*nSize/2);
			memset(pObj, 0, sizeof(OsmsUserLogoutRequest)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new OsmsUserLogoutRequest[nSize];
		}
	}
	else
		return new OsmsUserLogoutRequest;
}

/*
 * This static method delete a OsmsUserLogoutRequest type of object
 */
void Axis_Delete_OsmsUserLogoutRequest(OsmsUserLogoutRequest* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of OsmsUserLogoutRequest type of object
 */
int Axis_GetSize_OsmsUserLogoutRequest()
{
	return sizeof(OsmsUserLogoutRequest);
}

OsmsUserLogoutRequest::OsmsUserLogoutRequest()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
}

OsmsUserLogoutRequest::~OsmsUserLogoutRequest()
{
	/*delete any pointer and array members here*/
}
