/**	\file OsmsWebService.hpp

	Osms web service C++ stub.<br>

    The Initial Developer of the Original Code is Mutable, Inc. <br>
    Portions created by Mutable, Inc. are <br>
    Copyright (C) Mutable, Inc. 2002-2006.  All Rights Reserved. <p>

    Portions of this file were auto-generated by the Axis C++ 
	Web Service Generator (WSDL2Ws).<p>
	
*/

#if !defined(__OSMSWEBSERVICE_CLIENTSTUB_H__INCLUDED_)
#define __OSMSWEBSERVICE_CLIENTSTUB_H__INCLUDED_

#include <string>

#include <axis/client/Stub.hpp>
#include <axis/SoapFaultException.hpp>
#include <axis/ISoapFault.hpp>
AXIS_CPP_NAMESPACE_USE
#include "OsmsRegisterContentAssignIdentifierResponse.hpp"
#include "OsmsUserLoginRequest.hpp"
#include "OsmsRegisterDigitalItemInstanceRequest.hpp"
#include "OsmsUserLoginFault.hpp"
#include "OsmsGetContentKeyResponse.hpp"
#include "OsmsRegisterDigitalItemInstanceFault.hpp"
#include "OsmsQueryResponse.hpp"
#include "OsmsUserLogoutResponse.hpp"
#include "OsmsUserLogoutRequest.hpp"
#include "OsmsUserLogoutFault.hpp"
#include "OsmsRightsAuthorizationFault.hpp"
#include "OsmsRegisterContentAssignIdentifierFault.hpp"
#include "OsmsRegisterUserFault.hpp"
#include "OsmsRegisterContentAssignIdentifierRequest.hpp"
#include "OsmsLicenseFault.hpp"
#include "OsmsRegisterContentExistingIdentifierResponse.hpp"
#include "OsmsGetContentKeyRequest.hpp"
#include "OsmsQueryRequest.hpp"
#include "OsmsRegisterContentExistingIdentifierRequest.hpp"
#include "OsmsUserLoginResponse.hpp"
#include "OsmsLicenseResponse.hpp"
#include "OsmsRegisterUserRequest.hpp"
#include "OsmsRegisterDigitalItemInstanceResponse.hpp"
#include "OsmsGetContentKeyFault.hpp"
#include "OsmsRegisterContentExistingIdentifierFault.hpp"
#include "OsmsCreateUserFault.hpp"
#include "OsmsCreateUserResponse.hpp"
#include "OsmsCreateUserRequest.hpp"
#include "OsmsQueryFault.hpp"
#include "OsmsRegisterUserResponse.hpp"
#include "OsmsRightsAuthorizationResponse.hpp"
#include "OsmsLicenseRequest.hpp"
#include "OsmsRightsAuthorizationRequest.hpp"

class OsmsWebService : public Stub
{
public:
	/*STORAGE_CLASS_INFO*/ OsmsWebService(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP1_1);
	/*STORAGE_CLASS_INFO*/ OsmsWebService();
public:
	/*STORAGE_CLASS_INFO*/ virtual ~OsmsWebService();
public: 
	/*STORAGE_CLASS_INFO*/ OsmsQueryResponse* query(OsmsQueryRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsLicenseResponse* license(OsmsLicenseRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsUserLoginResponse* userLogin(OsmsUserLoginRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsUserLogoutResponse* userLogout(OsmsUserLogoutRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsCreateUserResponse* createUser(OsmsCreateUserRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsGetContentKeyResponse* getContentKey(OsmsGetContentKeyRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsRegisterContentAssignIdentifierResponse* registerContentAssignIdentifier(OsmsRegisterContentAssignIdentifierRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsRegisterContentExistingIdentifierResponse* registerContentExistingIdentifier(OsmsRegisterContentExistingIdentifierRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsRegisterDigitalItemInstanceResponse* registerDigitalItemInstance(OsmsRegisterDigitalItemInstanceRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsRegisterUserResponse* registerUser(OsmsRegisterUserRequest* Value0);
	/*STORAGE_CLASS_INFO*/ OsmsRightsAuthorizationResponse* rightsAuthorization(OsmsRightsAuthorizationRequest* Value0);

	void setServiceEndpoint(const std::string& uri);
	std::string getServiceEndpoint();

private:
	std::string serviceEndpoint;
};

#endif /* !defined(__OSMSWEBSERVICE_CLIENTSTUB_H__INCLUDED_)*/
