/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__OMADRMWS_CLIENTSTUB_H__INCLUDED_)
#define __OMADRMWS_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.hpp>
#include <axis/SoapFaultException.hpp>
#include <axis/ISoapFault.hpp>
AXIS_CPP_NAMESPACE_USE
#include "WSRORequest.hpp"
#include "WSROAcquisitionTrigger.hpp"
#include "WSRIHello.hpp"
#include "WSROResponse.hpp"
#include "WSRegistrationResponse.hpp"
#include "WSRegistrationRequest.hpp"
#include "WSInitialRORequest.hpp"
#include "WSDeviceHello.hpp"

class OMADRMWS :public Stub
{
public:
	OMADRMWS(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP1_1);
	OMADRMWS();
public:
	virtual ~OMADRMWS();
public: 
	WSRIHello* hello(WSDeviceHello* Value0);
	WSRegistrationResponse* registration(WSRegistrationRequest* Value0);
	WSROAcquisitionTrigger* initialRO(WSInitialRORequest* Value0);
	WSROResponse* roAcquisition(WSRORequest* Value0);
};

#endif /* !defined(__OMADRMWS_CLIENTSTUB_H__INCLUDED_)*/
