/*
 * Copyright 2003-2004 The Apache Software Foundation.

 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type WSRegistrationResponse
 */

#include "WSRegistrationResponse.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a WSRegistrationResponse type of object
 */
int Axis_Serialize_WSRegistrationResponse(WSRegistrationResponse* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_WSRegistrationResponse, ">", NULL);
	}
	else
	{
		bool blnIsNewPrefix = false;
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_WSRegistrationResponse, blnIsNewPrefix);
		if (!blnIsNewPrefix)
		{
			pSZ->serialize("<", Axis_TypeName_WSRegistrationResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_WSRegistrationResponse, "\">", NULL);
		}
		else
		{
			pSZ->serialize("<", Axis_TypeName_WSRegistrationResponse, " xsi:type=\"", sPrefix, ":",
				Axis_TypeName_WSRegistrationResponse, "\" xmlns:", sPrefix, "=\"",
				Axis_URI_WSRegistrationResponse, "\">", NULL);
		}
	}

	pSZ->serializeAsElement("msg", (void*)(param->msg), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_WSRegistrationResponse, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a WSRegistrationResponse type of object
 */
int Axis_DeSerialize_WSRegistrationResponse(WSRegistrationResponse* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->msg = pIWSDZ->getElementAsString("msg",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_WSRegistrationResponse(WSRegistrationResponse* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			WSRegistrationResponse* pNew = new WSRegistrationResponse[nSize];
			memcpy(pNew, pObj, sizeof(WSRegistrationResponse)*nSize/2);
			memset(pObj, 0, sizeof(WSRegistrationResponse)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new WSRegistrationResponse[nSize];
		}
	}
	else
		return new WSRegistrationResponse;
}

/*
 * This static method delete a WSRegistrationResponse type of object
 */
void Axis_Delete_WSRegistrationResponse(WSRegistrationResponse* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of WSRegistrationResponse type of object
 */
int Axis_GetSize_WSRegistrationResponse()
{
	return sizeof(WSRegistrationResponse);
}

WSRegistrationResponse::WSRegistrationResponse()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &msg, 0, sizeof( xsd__string));
}

WSRegistrationResponse::~WSRegistrationResponse()
{
	/*delete any pointer and array members here*/
}
