<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.mutable.com" xmlns:impl="http://ws.mutable.com" xmlns:intf="http://ws.mutable.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<!--WSDL created by Apache Axis version: 1.2.1
Built on Jun 14, 2005 (09:15:57 EDT)-->

   <wsdl:message name="helloRequest">

      <wsdl:part name="name" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="helloResponse">

      <wsdl:part name="helloReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="Hello">

      <wsdl:operation name="hello" parameterOrder="name">

         <wsdl:input name="helloRequest" message="impl:helloRequest"/>

         <wsdl:output name="helloResponse" message="impl:helloResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HelloSoapBinding" type="impl:Hello">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="hello">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="helloRequest">

            <wsdlsoap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.mutable.com"/>

         </wsdl:input>

         <wsdl:output name="helloResponse">

            <wsdlsoap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.mutable.com"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HelloService">

      <wsdl:port name="Hello" binding="impl:HelloSoapBinding">

         <wsdlsoap:address location="http://localhost:8080/openipmp/services/Hello"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
