libtool -static -o libopenipmp.la \
../../ext/openssl/lib/macosx/static/gcc33_openssl97b/libssl.a \
../../ext/openssl/lib/macosx/static/gcc33_openssl97b/libcrypto.a \
AuxData.o \
AuxData_Factory.o \
ClientManager.o \
UserRegistrationManager.o \
osmsMessageAcquireUserKeyStoreRequest.o \
osmsMessageAcquireUserKeyStoreResponse.o \
osmsMessageAcquireUserKeyStoreResponseError.o \
CipherContext.o \
ContentAuthorizationManager.o \
ContentIdentity.o \
ContentRegistrationContext.o \
CryptoManager.o \
DOI.o \
DOI_Factory.o \
DigitalSignature.o \
DigitalSignature_Factory.o \
Exception.o \
HashContext.o \
IPMP_ContentId_Factory.o \
IPMP_ContentIdentity.o \
IPMP_MediaContext.o \
IPMP_MetaData.o \
KeyTransport.o \
KeyTransport_Factory.o \
MPEGRELLicense.o \
MemMan.o \
ODRLLicense.o \
OlCharArray.o \
OlMemMan.o \
OlRaw.o \
RightsHost.o \
RightsHost_Factory.o \
SecurityManagerProxy.o \
UserContext.o \
XRMLLicense.o \
osmsMessage.o \
osmsMessageCreateUserRequest.o \
osmsMessageCreateUserResponse.o \
osmsMessageCreateUserResponseError.o \
osmsMessageGenericResponseError.o \
osmsMessageGetContentKeyRequest.o \
osmsMessageGetContentKeyResponse.o \
osmsMessageGetContentKeyResponseError.o \
osmsMessageLicenseRequest.o \
osmsMessageLicenseResponse.o \
osmsMessageLicenseResponseError.o \
osmsMessageQueryRequest.o \
osmsMessageQueryResponse.o \
osmsMessageRegisterContentAssignIdentifierRequest.o \
osmsMessageRegisterContentAssignIdentifierResponse.o \
osmsMessageRegisterContentAssignIdentifierResponseError.o \
osmsMessageRegisterContentExistingIdentifierRequest.o \
osmsMessageRegisterContentExistingIdentifierResponse.o \
osmsMessageRegisterContentExistingIdentifierResponseError.o \
osmsMessageRegisterDigitalItemInstanceRequest.o \
osmsMessageRegisterDigitalItemInstanceResponse.o \
osmsMessageRegisterDigitalItemInstanceResponseError.o \
osmsMessageRegisterUserRequest.o \
osmsMessageRegisterUserResponse.o \
osmsMessageRegisterUserResponseError.o \
osmsMessageRightsAuthorizationRequest.o \
osmsMessageRightsAuthorizationResponse.o \
osmsMessageUnknownRequestResponseError.o  \
osmsMessageUserLoginRequest.o \
osmsMessageUserLoginResponse.o \
osmsMessageUserLoginResponseError.o \
osmsMessageUserLogoutRequest.o \
osmsMessageUserLogoutResponse.o \
osmsMessageUserLogoutResponseError.o
