/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub Class for remote web service 
 */

#if !defined(__OMADRMWS_CLIENTSTUB_H__INCLUDED_)
#define __OMADRMWS_CLIENTSTUB_H__INCLUDED_

#include <axis/client/Stub.hpp>
#include <axis/SoapFaultException.hpp>
#include <axis/ISoapFault.hpp>
AXIS_CPP_NAMESPACE_USE
#include "WSAddContentKeyRequest.hpp"
#include "WSAddDeviceRightsRequest.hpp"
#include "WSAddContentKeyResponse.hpp"
#include "WSAddDeviceRightsResponse.hpp"

class OMADRMWS :public Stub
{
public:
	STORAGE_CLASS_INFO OMADRMWS(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol=APTHTTP1_1);
	STORAGE_CLASS_INFO OMADRMWS();
public:
	STORAGE_CLASS_INFO virtual ~OMADRMWS();
public: 
	STORAGE_CLASS_INFO WSAddContentKeyResponse* addContentKey(WSAddContentKeyRequest* Value0);
	STORAGE_CLASS_INFO WSAddDeviceRightsResponse* addDeviceRights(WSAddDeviceRightsRequest* Value0);
};

#endif /* !defined(__OMADRMWS_CLIENTSTUB_H__INCLUDED_)*/
